data:
  dataset: DetectionDataset
  dataset_path: ./Dataset_Old
  label_map:
    0: '0'
    1: 1+
    2: 2+
    3: 3+
    4: nt
  normalize_stains_train: false
  normalize_stains_val: false
  num_classes: 5
  train_filelist: ./Dataset_Old/splits/fold_0/train.csv
  val_filelist: ./Dataset_Old/splits/fold_0/val.csv
gpu: 0
logging:
  level: Debug
  log_comment: her2_classification
  log_dir: ./logs
  mode: offline
  notes: HER2 classification
  project: cellvit++
  wandb_dir: ./logs
model:
  hidden_dim: 256
random_seed: 42
training:
  batch_size: 64
  cache_cell_dataset: true
  drop_rate: 0.1
  early_stopping_patience: 10
  epochs: 50
  eval_every: 1
  mixed_precision: true
  optimizer: AdamW
  optimizer_hyperparameter:
    betas:
    - 0.9
    - 0.999
    lr: 0.0001
    weight_decay: 0.01
  scheduler:
    scheduler_type: exponential
