services:
  viewer:
    build: ./Viewer
    ports:
      - "80:3000"
    command: ["npm", "start", "--", "--host", "0.0.0.0"]
    networks:
      - base_network

  slide-provider:
    build: ./SlideProvider
    ports:
      - "3306:3306"
    command: ["uvicorn", "slide_provider:slide_endpoint", "--host", "0.0.0.0", "--port", "3306", "--reload"]
    networks:
      - base_network

networks:
  base_network:
    driver: bridge
