name: fastapi_patho
channels:
  - bioconda
  - defaults
  - conda-forge
dependencies:
  - openslide=4.0.0
  - python=3.10.13
  - pip:
      - cachetools==5.3.3
      - certifi==2024.2.2
      - fastapi==0.110.0
      - openslide-python
      - uvicorn
      - numpy
      - pathopatch
      - openslide-python>=1.3.1
